package seeders

import (
	"log"

	"app/models/setting"

	"github.com/Masterminds/squirrel"
	"github.com/jmoiron/sqlx"
)

func Settings(db *sqlx.DB, qb *squirrel.StatementBuilderType) {
	cols := []string{
		"id",
		"key",
		"value",
		"is_disabled",
		"is_readonly",
		"field_type",
		"data_type",
	}
	for i := range settings {
		values := []any{
			settings[i].ID,
			settings[i].Key,
			settings[i].Value,
			settings[i].IsDisabled,
			settings[i].IsReadOnly,
			settings[i].FieldType,
			settings[i].DataType,
		}
		genericSeeder(db, qb, "settings", cols, values)
	}
	if _, err := db.Exec(
		`SELECT setval('settings_id_seq', (SELECT MAX(id) FROM settings));`,
	); err != nil {
		log.Panicf(
			"error executing sql sequence update settings: %s",
			err.Error(),
		)
	}
	RunningSeedTable.Append(len(settings), "settings")
}

var settings = []setting.Model{
	{
		ID:         1,
		Key:        "app_name",
		Value:      "اسم التطبيق",
		IsDisabled: false,
		IsReadOnly: false,
		FieldType:  "text",
		DataType:   "string",
	},
	{
		ID:         2,
		Key:        "about",
		Value:      "عن التطبيق",
		IsDisabled: false,
		IsReadOnly: false,
		FieldType:  "textarea",
		DataType:   "string",
	},
	{
		ID:         3,
		Key:        "rules",
		Value:      "قوانين التطبيق",
		IsDisabled: false,
		IsReadOnly: false,
		FieldType:  "textarea",
		DataType:   "string",
	},
	{
		ID:         4,
		Key:        "app_phone",
		Value:      "+218910001122",
		IsDisabled: false,
		IsReadOnly: false,
		FieldType:  "text",
		DataType:   "string",
	},
	{
		ID:         5,
		Key:        "app_whatsapp_url",
		Value:      "whatsapp/910001122",
		IsDisabled: false,
		IsReadOnly: false,
		FieldType:  "text",
		DataType:   "string",
	},
	{
		ID:         6,
		Key:        "app_facebook_url",
		Value:      "facebook.com/app",
		IsDisabled: false,
		IsReadOnly: false,
		FieldType:  "text",
		DataType:   "string",
	},
	{
		ID:         7,
		Key:        "app_telegram_url",
		Value:      "telegram.com/910001122",
		IsDisabled: false,
		IsReadOnly: false,
		FieldType:  "text",
		DataType:   "string",
	},
	{
		ID:         8,
		Key:        "app_instagram_url",
		Value:      "instagram.com/app",
		IsDisabled: false,
		IsReadOnly: false,
		FieldType:  "text",
		DataType:   "string",
	},
	{
		ID:         9,
		Key:        "app_website_url",
		Value:      "wwww.app.ly",
		IsDisabled: false,
		IsReadOnly: false,
		FieldType:  "text",
		DataType:   "string",
	},
	{
		ID:         10,
		Key:        "app_email_url",
		Value:      "info@app.ly",
		IsDisabled: false,
		IsReadOnly: false,
		FieldType:  "text",
		DataType:   "string",
	},
	{
		ID:         11,
		Key:        "app_twitter_url",
		Value:      "twitter.com/app",
		IsDisabled: false,
		IsReadOnly: false,
		FieldType:  "text",
		DataType:   "string",
	},
	{
		ID:         12,
		Key:        "app_logo",
		Value:      "path/image.jpg",
		IsDisabled: false,
		IsReadOnly: false,
		FieldType:  "file",
		DataType:   "string",
	},
	{
		ID:         13,
		Key:        "app_color_primary",
		Value:      "#6C04FC",
		IsDisabled: false,
		IsReadOnly: false,
		FieldType:  "color",
		DataType:   "string",
	},
	{
		ID:         14,
		Key:        "app_color_secondary",
		Value:      "#4E6E5D",
		IsDisabled: false,
		IsReadOnly: false,
		FieldType:  "color",
		DataType:   "string",
	},
	{
		ID:         15,
		Key:        "app_color_on_primary",
		Value:      "#C2E7DA",
		IsDisabled: false,
		IsReadOnly: false,
		FieldType:  "color",
		DataType:   "string",
	},
	{
		ID:         16,
		Key:        "app_color_on_secondary",
		Value:      "#F1FFE7",
		IsDisabled: false,
		IsReadOnly: false,
		FieldType:  "color",
		DataType:   "string",
	},
	{
		ID:         17,
		Key:        "app_app_store_url",
		Value:      "https://apps.apple.com/us/app",
		IsDisabled: false,
		IsReadOnly: false,
		FieldType:  "text",
		DataType:   "string",
	},
	{
		ID:         18,
		Key:        "app_google_play_url",
		Value:      "https://play.google.com/store/apps",
		IsDisabled: false,
		IsReadOnly: false,
		FieldType:  "text",
		DataType:   "string",
	},
	{
		ID:         19,
		Key:        "main_hero",
		Value:      "path/image.jpg",
		IsDisabled: false,
		IsReadOnly: false,
		FieldType:  "file",
		DataType:   "string",
	},
	{
		ID:         20,
		Key:        "main_title",
		Value:      "Main Title",
		IsDisabled: false,
		IsReadOnly: false,
		FieldType:  "text",
		DataType:   "string",
	},
	{
		ID:         21,
		Key:        "main_subtitle",
		Value:      "Main Subtitle",
		IsDisabled: false,
		IsReadOnly: false,
		FieldType:  "text",
		DataType:   "string",
	},
	{
		ID:         22,
		Key:        "main_summary",
		Value:      "Main Summary",
		IsDisabled: false,
		IsReadOnly: false,
		FieldType:  "text",
		DataType:   "string",
	},
	{
		ID:         23,
		Key:        "main_call_to_action",
		Value:      "Register Now!",
		IsDisabled: false,
		IsReadOnly: false,
		FieldType:  "text",
		DataType:   "string",
	},
	{
		ID:         24,
		Key:        "app_privacy_policy",
		Value:      "privacy policy",
		IsDisabled: false,
		IsReadOnly: false,
		FieldType:  "text",
		DataType:   "string",
	},

	// TLync settings
	{
		ID:         25,
		Key:        "tlync_endpoint",
		Value:      "https://c7drkx2ege.execute-api.eu-west-2.amazonaws.com",
		IsDisabled: true,
		IsReadOnly: false,
		FieldType:  "text",
		DataType:   "string",
	},
	{
		ID:         26,
		Key:        "tlync_token",
		Value:      "qS00000000000000000000000000000000000000",
		IsDisabled: true,
		IsReadOnly: false,
		FieldType:  "text",
		DataType:   "string",
	},
	{
		ID:         27,
		Key:        "tlync_store_id",
		Value:      "wL00000000000000000000000000000000000000000000000000000000000000",
		IsDisabled: true,
		IsReadOnly: false,
		FieldType:  "text",
		DataType:   "string",
	},
	{
		ID:         28,
		Key:        "tlync_front_url",
		Value:      "https://sadeem-tech.com",
		IsDisabled: true,
		IsReadOnly: false,
		FieldType:  "text",
		DataType:   "string",
	},
	// OTP settings
	{
		ID:         29,
		Key:        "sadeem_otp_url",
		Value:      "https://otp.sadeem-factory.com",
		IsDisabled: true,
		IsReadOnly: false,
		FieldType:  "text",
		DataType:   "string",
	},
	{
		ID:         30,
		Key:        "sadeem_otp_jwt",
		Value:      "qS00000000000000000000000000000000000000",
		IsDisabled: true,
		IsReadOnly: false,
		FieldType:  "textarea",
		DataType:   "string",
	},
	{
		ID:         31,
		Key:        "sadeem_otp_env",
		Value:      "development",
		IsDisabled: true,
		IsReadOnly: false,
		FieldType:  "textarea",
		DataType:   "string",
	},
	{
		ID:         32,
		Key:        "sadeem_otp_key",
		Value:      "qS00000000000000000000000000000000000000",
		IsDisabled: true,
		IsReadOnly: false,
		FieldType:  "textarea",
		DataType:   "string",
	},
	{
		ID:         33,
		Key:        "payment_gateway_endpoint",
		Value:      "https://tyrian-ant.sadeem-lab.com/api/v1",
		IsDisabled: true,
		IsReadOnly: false,
		FieldType:  "text",
		DataType:   "string",
	},
	{
		ID:         34,
		Key:        "payment_gateway_api_key",
		Value:      "qS00000000000000000000000000000000000000",
		IsDisabled: true,
		IsReadOnly: false,
		FieldType:  "text",
		DataType:   "string",
	},
}
